"""favorites

Revision ID: 34263525cc95
Revises: 078bb6185a9b
Create Date: 2026-05-13 12:24:18.529239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34263525cc95'
down_revision: Union[str, Sequence[str], None] = '078bb6185a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('price_id', sa.UUID(), nullable=True), schema='db_schema')
    op.create_foreign_key(None, 'favorite', 'prices', ['price_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', schema='db_schema', type_='foreignkey')
    op.drop_column('favorite', 'price_id', schema='db_schema')
    # ### end Alembic commands ###
