"""customs

Revision ID: cf79e2017822
Revises: 15123cd8cbfa
Create Date: 2026-04-30 15:20:58.254376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf79e2017822'
down_revision: Union[str, Sequence[str], None] = '15123cd8cbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_cart_drinks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('cart_drink_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_drink_id'], ['db_schema.cart_drinks.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['db_schema.ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('custom_cart_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('cart_food_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_food_id'], ['db_schema.cart_foods.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['db_schema.ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.drop_table('carts', schema='db_schema')
    op.drop_table('cart', schema='db_schema')
    op.drop_table('carts_products', schema='db_schema')
    op.add_column('cart_drinks', sa.Column('user_id', sa.UUID(), nullable=False), schema='db_schema')
    op.drop_constraint(op.f('cart_drinks_cart_id_fkey'), 'cart_drinks', schema='db_schema', type_='foreignkey')
    op.create_foreign_key(None, 'cart_drinks', 'users', ['user_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    op.drop_column('cart_drinks', 'cart_id', schema='db_schema')
    op.add_column('cart_foods', sa.Column('user_id', sa.UUID(), nullable=False), schema='db_schema')
    op.drop_constraint(op.f('cart_foods_cart_id_fkey'), 'cart_foods', schema='db_schema', type_='foreignkey')
    op.create_foreign_key(None, 'cart_foods', 'users', ['user_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    op.drop_column('cart_foods', 'unit_price', schema='db_schema')
    op.drop_column('cart_foods', 'cart_id', schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_foods', sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False), schema='db_schema')
    op.add_column('cart_foods', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='db_schema')
    op.drop_constraint(None, 'cart_foods', schema='db_schema', type_='foreignkey')
    op.create_foreign_key(op.f('cart_foods_cart_id_fkey'), 'cart_foods', 'carts', ['cart_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    op.drop_column('cart_foods', 'user_id', schema='db_schema')
    op.add_column('cart_drinks', sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False), schema='db_schema')
    op.drop_constraint(None, 'cart_drinks', schema='db_schema', type_='foreignkey')
    op.create_foreign_key(op.f('cart_drinks_cart_id_fkey'), 'cart_drinks', 'carts', ['cart_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    op.drop_column('cart_drinks', 'user_id', schema='db_schema')
    op.create_table('carts_products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drink_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('food_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['db_schema.carts.id'], name=op.f('carts_products_cart_id_fkey')),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], name=op.f('carts_products_drink_id_fkey')),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], name=op.f('carts_products_food_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_products_pkey')),
    schema='db_schema'
    )
    op.create_table('cart',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['db_schema.users.id'], name=op.f('cart_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_pkey')),
    schema='db_schema'
    )
    op.create_table('carts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['db_schema.users.id'], name=op.f('carts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pkey')),
    schema='db_schema'
    )
    op.drop_table('custom_cart_foods', schema='db_schema')
    op.drop_table('custom_cart_drinks', schema='db_schema')
    # ### end Alembic commands ###
