"""price_table

Revision ID: f0093ea7c966
Revises: 8250477f8ee0
Create Date: 2026-04-21 13:02:04.496708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0093ea7c966'
down_revision: Union[str, Sequence[str], None] = '8250477f8ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['db_schema.drinks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.drop_column('drinks', 'price', schema='db_schema')
    op.drop_column('drinks', 'volume', schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True), schema='db_schema')
    op.add_column('drinks', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='db_schema')
    op.drop_table('prices', schema='db_schema')
    # ### end Alembic commands ###
