"""foods_drinks

Revision ID: 15123cd8cbfa
Revises: 50136606b0cb
Create Date: 2026-04-30 10:26:38.359644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15123cd8cbfa'
down_revision: Union[str, Sequence[str], None] = '50136606b0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['db_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('cart_drinks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('drink_id', sa.UUID(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['db_schema.carts.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('cart_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['db_schema.carts.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('carts_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('drink_id', sa.UUID(), nullable=True),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['db_schema.carts.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('images_drinks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drink_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('images_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('order_drinks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('drink_id', sa.UUID(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['db_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.create_table('order_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['db_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='db_schema'
    )
    op.drop_table('order_products', schema='db_schema')
    op.drop_table('images', schema='db_schema')
    op.add_column('orders', sa.Column('count', sa.Integer(), nullable=False), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'count', schema='db_schema')
    op.create_table('images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drink_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('food_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], name=op.f('images_drink_id_fkey')),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], name=op.f('images_food_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey')),
    schema='db_schema'
    )
    op.create_table('order_products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drink_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('food_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['db_schema.drinks.id'], name=op.f('order_products_drink_id_fkey')),
    sa.ForeignKeyConstraint(['food_id'], ['db_schema.food.id'], name=op.f('order_products_food_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['db_schema.orders.id'], name=op.f('order_products_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_products_pkey')),
    schema='db_schema'
    )
    op.drop_table('order_foods', schema='db_schema')
    op.drop_table('order_drinks', schema='db_schema')
    op.drop_table('images_foods', schema='db_schema')
    op.drop_table('images_drinks', schema='db_schema')
    op.drop_table('carts_products', schema='db_schema')
    op.drop_table('cart_foods', schema='db_schema')
    op.drop_table('cart_drinks', schema='db_schema')
    op.drop_table('carts', schema='db_schema')
    # ### end Alembic commands ###
