"""ingredients

Revision ID: 0e515d160f9a
Revises: 3371c25621ef
Create Date: 2026-04-22 10:15:18.531810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e515d160f9a'
down_revision: Union[str, Sequence[str], None] = '3371c25621ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('ingredients', sa.String(), nullable=True), schema='db_schema')
    op.add_column('food', sa.Column('ingredients', sa.String(), nullable=True), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'ingredients', schema='db_schema')
    op.drop_column('drinks', 'ingredients', schema='db_schema')
    # ### end Alembic commands ###
