"""favorite_сгыещьы

Revision ID: 6ed33a83e861
Revises: 34263525cc95
Create Date: 2026-05-13 15:34:42.800913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed33a83e861'
down_revision: Union[str, Sequence[str], None] = '34263525cc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_customs', sa.Column('price_id', sa.UUID(), nullable=True), schema='db_schema')
    op.create_foreign_key(None, 'favorite_customs', 'prices', ['price_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_customs', schema='db_schema', type_='foreignkey')
    op.drop_column('favorite_customs', 'price_id', schema='db_schema')
    # ### end Alembic commands ###
