"""user_update

Revision ID: 50136606b0cb
Revises: 0e515d160f9a
Create Date: 2026-04-29 12:06:55.171164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50136606b0cb'
down_revision: Union[str, Sequence[str], None] = '0e515d160f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False), schema='db_schema')
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=False), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone', schema='db_schema')
    op.drop_column('users', 'email', schema='db_schema')
    # ### end Alembic commands ###
