"""price

Revision ID: 21ed06c572aa
Revises: 6ed33a83e861
Create Date: 2026-05-18 14:17:51.157585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ed06c572aa'
down_revision: Union[str, Sequence[str], None] = '6ed33a83e861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_products', sa.Column('price_id', sa.UUID(), nullable=True), schema='db_schema')
    op.create_foreign_key(None, 'cart_products', 'prices', ['price_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    op.add_column('custom_cart', sa.Column('price_id', sa.UUID(), nullable=True), schema='db_schema')
    op.create_foreign_key(None, 'custom_cart', 'prices', ['price_id'], ['id'], source_schema='db_schema', referent_schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_cart', schema='db_schema', type_='foreignkey')
    op.drop_column('custom_cart', 'price_id', schema='db_schema')
    op.drop_constraint(None, 'cart_products', schema='db_schema', type_='foreignkey')
    op.drop_column('cart_products', 'price_id', schema='db_schema')
    # ### end Alembic commands ###
